services:
  server:
    build:
      context: .
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PASSWORD=${CODE_PASSWORD}
    volumes:
      - ./config:/config
      - ./projects:/config/workspace
    ports:
      - "1337:8443"
    restart: unless-stopped
