services:
  server:
    build:
      context: .
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PASSWORD=dev
    volumes:
      - './projects:/home/coder/project'
      - './config:/config'
      - './config-defaults/data/User/settings.json:/config/data/User/settings.json'
      - './ssh-keys:/config/.ssh:ro'
    ports:
      - '1337:8443'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
